---
title: "PredMachLearnProj"
author: "Elliot Smith"
date: "December 23, 2015"
output: html_document
---

### Load necessary packages and set seed

```{r}
require(caret)
require(ggplot2)
require(dplyr)
require(randomForest)
set.seed(1234)
```

### Read in the data sets

```{r}
url1 <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
url2 <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
training_raw <- read.csv(url1)
testing_raw <- read.csv(url2)
```

### Explore the training data

```{r}
#Basic exploration
training <- training_raw
testing <- testing_raw
dim(training)
summary(training$classe)
str(training)

#Explore variables' classes
classes <- as.data.frame(sapply(training, class))
str(classes)
table(classes)
```

### Clean the training data

```{r}
#Discard unnecessary variables
training <- select(training, roll_belt:classe)
dim(training)

#Convert all variables to numeric, except classe
training <- mutate_each(training, funs(as.character), -classe)
training <- mutate_each(training, funs(as.numeric), -classe)
classes <- as.data.frame(sapply(training, class))
str(classes)
table(classes)

#Exclude variables that have NA's
training <- training[,colSums(is.na(training)) == 0]
dim(training)
```

### Build the model with cross validation

```{r}
#Train using Random Forest with cross validation
model1 <- train(classe ~ ., data = training, method = "rf", na.action = na.omit, trControl = trainControl(method = "cv", number = 5))
```

### Evaluate model

```{r}
model1
model1$finalModel
```

###It looks pretty good! 

###Make prediction on testing data

```{r}
testing$classe <- predict(model1, newdata = testing)
testing$classe
```